

spring:
  zipkin:
    baseUrl: ${vcap.services.zipkin.credentials.url}
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0


ingest:
   url: ${vcap.services.ingest.credentials.url}
process:
   url: ${vcap.services.process.credentials.url}
publish:
   url: ${vcap.services.publish.credentials.url}