management:
  security:
    enabled: false


server:
  port: 8084

spring:
    
  datasource:
    url: jdbc:mysql://localhost:3306/ingest
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    baseUrl: ${vcap.services.zipkin.credentials.url}
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0


    

    
