server:
  port: 8765
  
spring:
  profiles:
    active: local


info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
 

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

logging:
  level: 
    org.springframework: DEBUG


zuul:
  prefix: /api
  routes:
    status:
      path: /status/**
      serviceId: STATUS-SERVICE
    ingest:
      path: /ingest/**
      serviceId: INGEST-SERVICE  
    
#---
#spring:
#  profiles:
#    active: cloud
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: https://eureka-service-cctv.cfapps.io/eureka

